products = [
    ("Salad", "Organic Salad", 299),
    ("Salad", "Fruit Bowls", 299),
    ("Salad", "Fruit Cocktail", 350),
    ("Salad", "Grilled Chicken Salad", 349),

    ("Snacks", "French Fries", 249),
    ("Snacks", "Cheese Ball", 425),
    ("Snacks", "Salt & Pepper Mushroom", 400),
    ("Snacks", "Mustang Aalu", 299),
    ("Snacks", "Chips Chilli", 225),
    ("Snacks", "Paneer Chilli", 475),
    ("Snacks", "Fried Corn", 350),
    ("Snacks", "Chicken Timur", 550),
    ("Snacks", "Chicken Nuggets", 349),
    ("Snacks", "Dynamite Chicken", 499),
    ("Snacks", "Chicken Chilli", 399),
    ("Snacks", "Boiled Chicken", 419),
    ("Snacks", "Chicken Lollipop", 580),
    ("Snacks", "Hot Wings", 550),
    ("Snacks", "Ginger Fish", 500),
    ("Snacks", "Tawa Fish", 950),

    ("Burger / Sandwich / Wrap", "Burger (Veg)", 199),
    ("Burger / Sandwich / Wrap", "Burger (Chicken)", 299),
    ("Burger / Sandwich / Wrap", "Alu Tikki", 199),
    ("Burger / Sandwich / Wrap", "Crispy Chicken Burger", 499),
    ("Burger / Sandwich / Wrap", "Veg Sandwich", 300),
    ("Burger / Sandwich / Wrap", "Paneer Sandwich", 350),
    ("Burger / Sandwich / Wrap", "Grilled Chicken Sandwich", 549),
    ("Burger / Sandwich / Wrap", "Wrap (Veg)", 199),
    ("Burger / Sandwich / Wrap", "Wrap (Chicken)", 299),

    ("Pasta", "Spaghetti Bolognese", 450),
    ("Pasta", "Pesto Fungi", 499),
    ("Pasta", "Spaghetti Carbonara", 499),
    ("Pasta", "Spaghetti Napolitana", 399),

    ("Pizza", "Margarita", 549),
    ("Pizza", "Fungi", 599),
    ("Pizza", "Pepperoni", 649),
    ("Pizza", "Spicy Chicken", 649),
    ("Pizza", "Meat Lovers", 699),
]